# Copyright (c) 2026. Yin-Jinlong@github
# MPL-2.0

config("riu_ast_public") {
  include_dirs = [
    "//riu",
    "//riu/include",
    "//third_party/toml11/single_include",
    "//third_party/utfcpp/source",
  ]
}

static_library("riu_ast") {
  public_configs = [ ":riu_ast_public" ]

  sources = [
    "diagnostic.cpp",
    "mangler.cpp",
    "mod_decl.cpp",
    "name_lookup.cpp",
    "riu.cpp",
    "syntax_diag.cpp",
    "type_intern.cpp",
    "type_path.cpp",
    "rd/dump.cpp",
    "rd/flat.cpp",
    "rd/parser.cpp",
    "rd/scanner.cpp",
    "rd/token.cpp",
    "rd_builder.cpp",
    "rd_builder_decl.cpp",
    "rd_builder_expr.cpp",
    "rd_builder_stmt.cpp",
    "node/ast_visitor.cpp",
    "node/expr_node.cpp",
    "node/file_node.cpp",
    "node/fn_node.cpp",
    "node/global_const_node.cpp",
    "node/global_var_node.cpp",
    "node/literal_node.cpp",
    "node/node.cpp",
    "node/statement_node.cpp",
    "node/struct_node.cpp",
    "node/type_node.cpp",
  ]
}

executable("riu-ast") {
  output_dir = "$root_out_dir/bin"
  defines = [ "RIU_VERSION=\"$riu_version_str\"" ]
  deps = [ "//riu/frontend:riu_frontend" ]
  include_dirs = [ "//third_party/cli11/include" ]
  sources = [ "ast_main.cpp" ]
}
