# Copyright (c) 2026. Yin-Jinlong@github
# MPL-2.0

config("riu_frontend_public") {
  include_dirs = [
    ".",
    "//third_party/utfcpp/source",
    "//third_party/toml11/single_include",
    "//third_party/nlohmann_json/single_include",
  ]
  defines = [
    "UNICODE",
    "NOMINMAX",
  ]
}

static_library("riu_frontend") {
  public_configs = [ ":riu_frontend_public" ]
  public_deps = [
    "//riu/analyzer:riu_analyzer",
    "//riu/ast:riu_ast",
    "//riu/generic:riu_generic",
  ]
  sources = [
    "pass/pass.cpp",
    "sema/call_resolve.cpp",
    "sema/const_eval.cpp",
    "sema/name_resolver.cpp",
    "sema/sema_check.cpp",
    "sema/sema_expr.cpp",
    "sema/sema_pass.cpp",
    "sema/sema_pass_detail.cpp",
    "sema/sema_stmt.cpp",
    "sema/type_of_call.cpp",
    "sema/type_of_ctrl.cpp",
    "sema/type_of_dot.cpp",
    "sema/type_of_name.cpp",
    "sema/type_of_ops.cpp",
    "sema/type_of_rest.cpp",
    "sema/type_of_struct.cpp",
    "tools/pkg_cache.cpp",
    "tools/sdk_loader.cpp",
    "tools/format/doc.cpp",
    "tools/format/printer.cpp",
    "tools/format/render.cpp",
    "tools/format/trivia.cpp",
  ]
}
