# Copyright (c) 2026. Yin-Jinlong@github
# MPL-2.0

pool("console") {
  depth = 1
}

group("default") {
  deps = [
    "//riu/ast:riu-ast",
    "//riu/check:riu-check",
    "//riu/lsp:riu-lsp",
    "//riu/test-runner:riu-test-runner",
    "//riu/riu:riu",
  ]
}

group("all") {
  deps = [ ":default" ]
}
