set(LLVM_ROOT "${LIBS_DIR}/llvm/llvm" CACHE PATH "")
set(LLD_ROOT "${LIBS_DIR}/llvm/lld" CACHE PATH "")
set(ZLIB_ROOT "${LIBS_DIR}/zlib" CACHE PATH "")
set(ZLIB_LIBRARY zlib CACHE PATH "")

set(LLVM_INCLUDE_EXAMPLES OFF)
set(LLVM_INCLUDE_TESTS OFF)
set(LLVM_INCLUDE_BENCHMARKS OFF)
set(LLVM_ENABLE_PROJECTS "lld" CACHE STRING "" FORCE)
set(LLVM_ENABLE_RUNTIMES "libc" CACHE STRING "" FORCE)
set(LLVM_ENABLLLVM_ENABLE_RTTI OFF)
set(LLVM_ENABLE_EH OFF)
set(CMAKE_INTERPROCEDURAL_OPTIMIZATION TRUE)


set(Clang_DIR ${LLVM_ROOT})

add_subdirectory("${LIBS_DIR}/zlib" ${LIBS_BIN_DIR}/zlib)
add_subdirectory("${LIBS_DIR}/llvm/llvm" ${LIBS_BIN_DIR}/llvm)

list(APPEND LLVM_INCLUDE_DIR
        "${LLVM_ROOT}/include"
        "${LLD_ROOT}/include"
        "${LIBS_BIN_DIR}/llvm/include"
        )

set(LLVM_INCLUDE_DIR ${LLVM_INCLUDE_DIR} PARENT_SCOPE)

