# Copyright (c) 2026. Yin-Jinlong@github
# MPL-2.0

config("yux_lsp_public") {
  include_dirs = [ "//yux" ]
}

executable("yux-lsp") {
  output_dir = "$root_out_dir/bin"
  defines = [ "YUX_VERSION=\"$yux_version_str\"" ]
  configs += [ ":yux_lsp_public" ]
  deps = [ "//yux/frontend:yux_frontend" ]
  sources = [
    "completion.cpp",
    "document.cpp",
    "lsp_io.cpp",
    "lsp_main.cpp",
    "lsp_server.cpp",
    "position.cpp",
    "semantic_tokens.cpp",
    "symbol_lookup.cpp",
    "workspace.cpp",
  ]
}
